channel_name: general
bot_name: Flexbot
webserver_port: 8080

office_hours:
 "on": No
 begin: 9
 end: 17

debug: No

callouts:
 time_between:
  min_time: 17
  max_time: 23
 num_people: 3
 group_callout_chance: 0.05

exercises:
 -
  id: 0
  name: pushups
  min_reps: 15
  max_reps: 20
  units: rep
  info: |
    *How to set up for a proper push up*

    When it comes to push ups, your form is crucial. Each push up needs to be done perfectly so that your total reps measured from workout to workout are on equal footing. If you did thirty perfect push ups two days ago, and then today you did sixty push ups by only going down halfway, sticking your ass up in the air, etc., it's absolutely impossible to tell if you got any stronger.

    Here's how to get set up to do a push up:

    - When down on the ground, set your hands at a distance that is slightly wider than shoulder-width apart. Your hands should not be rotated: this reduces the ability to generate torque and increases the chance of improper elbow/wrist alignment, which in turn might lead to injury.
    - Your feet should be set up in a way that feels right and comfortable to you. For some, that might be shoulder width apart. For others, it might be that the feet are touching.  Generally speaking, the wider apart your feet, the more stable you'll be for your push ups.
    - Think of your body as one giant straight line - from the top of your head down through your heels. Your butt shouldn't be sticking way up in the air or sagging.
    - If you have a problem getting the proper form with your body, try this (yes I'm serious): clench your butt, and then tighten your abs. Your core will be engaged, and your body should be in that straight line. If you've been doing push ups incorrectly, this might be a big change for you.
    - Your head should be looking slightly ahead of you, not straight down (yeah I know I'm looking straight down in my top picture, I hadn't started yet!). I read somewhere that said "if you're doing them right, your chin should be the first part of your head to touch the floor, not your nose." Looking up helps you keep your body in line, but feel free to look down if that helps you concentrate more.
    - At the top of your push up, your arms should be straight and supporting your weight. You're now ready to do a push up.

    *How to complete a push up*

    Alright, now that you're actually all set up and eager to begin, let's get you through one repetition. Remember that good form is crucial, so keep your focus through each movement and start to set good habits.

    Here's how to complete one repetition of a push up:

    - With your arms straight, butt clenched, and abs braced, steadily lower yourself until your elbows are at a 90 degree angle or smaller. Depending on your level of experience, age, and flexibility, 90 degrees might be the lowest you're able to go. Personally, I like to go down until my chest (not my face), hits the floor.  That way, I know I'm going the same distance each and every time.
    - Try not to let your elbows go flying way out with each repetition. Keep them relatively close to your body, and keep note of when they start to fly out when you get tired.
    - Once your chest touches the floor (or your arms go down to a 90 degree angle), pause slightly and then explode back up until you're back in the same position.
    - Congratulations, you just did a proper push up. Do as many as you can until you start to feel your form slip (even slightly); you are done for that set. Ten good push ups and 5 crappy ones are tough to quantify against eleven good push ups. If you can only do ten of something, write down your results and aim for 11 next time. Perfect form allows you to keep track of your improvements week over week.
 -
  id: 1
  name: planks
  min_reps: 40
  max_reps: 60
  units: second
  info: |
    *How to do planks*
    - Get in the pushup position, only put your forearms on the ground instead of your hands. Your elbows should line up directly underneath your shoulders. Toes on the ground.
    - Squeeze your glutes and tighten your abdominals.
    - Keep a neutral neck and spine.
    - Create a straight, strong line from head to toes - a plank, if you will.
    - Hold that position until the time is up!

    *Things to Remember:*
    - Don't let your hips sag down to the ground. Sagging hips makes the exercise initially easier, but it's not a plank and it defeats the purpose of the exercise.
    - Look down at the ground. This is a good prompt for maintaining a neutral neck position.
    - When your form begins to suffer, pull the plug. You're only benefiting from the plank by actually doing the plank.
 -
  id: 2
  name: wall sit
  min_reps: 40
  max_reps: 50
  units: second
  info: |
    *How to do wall sits:*
    - Stand with your back against a wall, placing your feet about two feet out in front of you. Feet should be hip-distance apart.
    - Bending your knees, slide your back down the wall until your knees are at 90 degree angles. Your knee joints should be over your ankle joints, so you may need to inch your feet further from the wall to create proper alignment. Your thighs should remain parallel.
    - Hold for the specified duration.
    - To make this move more challenging, alternate between lifting your left heel for a few seconds and then your right. This helps to target your calves.
 -
  id: 3
  name: chair dips
  min_reps: 15
  max_reps: 30
  units: rep
  info: |
    *How to do chair dips:*
    For this workout, all you need is a elevated surface that's approximately knee high, such as a bench press, a stable chair (hence the alternative name chair dips), or a park bench. Prior to starting this exercise, it's advised to stretch for push-ups. Lets get started!

    - The easiest way to perform bench dips is to begin in the most obvious position. While seated on the edge your chair, place both hands by your side right next to your thighs and clasp the edge of the seat. Using your arms, push your butt up off the chair whilst maintaining a firm grip. With your arms fully extended and your butt off the chair, extend your legs directly in front of you so that your knees are no longer bent. This will be your starting position.
    - Lower yourself by bending your elbows until your triceps and forearms are perpendicular to each other (90 degrees). Make sure your feet aren't sliding and let your hips "hang".
    - Using your triceps, lift yourself back to the starting position. (See Step 1).
    - Repeat the above sequence for the desired amount of repetitions.

    Once you've become familiar with the normal bench dips and you're up for a challenge, you can progress to bench dips with elevated legs. This variation puts a lot more stress on the triceps and as a result, works your muscles harder.
 -
  id: 4
  name: calf raises
  min_reps: 20
  max_reps: 30
  units: rep
  info: |
    *How to do calf raises:*
    - Stand on the edge of a step, or, if you have a step-aerobics platform, place two sets of risers underneath the platform.
    - Stand tall with your abdominals pulled in, the balls of your feet firmly planted on the step, and your heels hanging over the edge.
    - Rest your hands against a wall or a sturdy object for balance.
    - Raise your heels a few inches above the edge of the step so that you're on your tiptoes.
    - Hold the position for a moment, and then lower your heels below the platform, feeling a stretch in your calf muscles.
  
    *Tips for doing the calf raise*
    - Lift as high as you can onto your toes and lower your heels down as much as your ankle flexibility allows.
    - Push evenly through the entire width of your foot. Don't push off from your big toe or the outside edge of your feet.


user_exercise_limit: 3
